<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="readme" nsURI="http://it.univaq.disim.msr.datashowcase/readme"
    nsPrefix="readme">
  <eClassifiers xsi:type="ecore:EClass" name="Gitome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//GitHubRepository" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitHubRepository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repository" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceDataset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fork" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stars" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languages" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topics" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainReadme" eType="#//Readme"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Readme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="raw_content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeCells" upperBound="-1"
        eType="#//CodeCells" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textCells" upperBound="-1"
        eType="#//TextCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCells">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CodeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CodeType">
    <eLiterals name="CODE_SPAN"/>
    <eLiterals name="IMAGE" value="1"/>
    <eLiterals name="LINK" value="3" literal="LINK"/>
    <eLiterals name="IN_LINE_HTML" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextCell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TextType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextType">
    <eLiterals name="EMPHASIS" value="1" literal="EMPHASIS"/>
    <eLiterals name="STRONG_EMPHASIS" value="2"/>
    <eLiterals name="RAW_TEXT" value="3"/>
  </eClassifiers>
</ecore:EPackage>
